# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7781f0d89dd91e3c2077a60be8b1f351320473df95eb244fe787e7118ba67cf1d2a32ff541791ab223f92d9cd45b3b7ce7c42038468d54e3a9bafa32031a3359

test:
  secret_key_base: a107a9a56d1544aafbef3436b0644a0bec610b707abb65fa14ceaa3dffb458552ea3e8ff97e83fca96c65278b0da848f6ee2a8dfe5f7a070ca94819d8817814c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
